### ISSUE TITLE
[BUG] return {"f1": float(score) if score.size == 1 else score}

### ISSUE THREAD

**Issue by Mikeriess** [ScandEval/ScandEval#643] opened 2024-12-13 08:30 UTC
### 🐛 Describe the bug

When benchmarking from python 3.11, using the latest version of ScandEval[all] I get the following error:

```
(app-root) scandeval --model norallm/normistral-7b-warm --task sentiment-classification --language da
2024-12-13 08:24:51 ⋅ Benchmarking norallm/normistral-7b-warm on the truncated version of the Danish sentiment classification dataset AngryTweets
2024-12-13 08:24:51 ⋅ Loading model...
Loading safetensors checkpoint shards:   0% Completed | 0/3 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:  33% Completed | 1/3 [00:10<00:21, 10.61s/it]
Loading safetensors checkpoint shards:  67% Completed | 2/3 [00:24<00:12, 12.55s/it]
Loading safetensors checkpoint shards: 100% Completed | 3/3 [00:34<00:00, 11.48s/it]
Loading safetensors checkpoint shards: 100% Completed | 3/3 [00:34<00:00, 11.57s/it]

2024-12-13 08:25:43 ⋅ The model has 7,248,023,552 parameters, a vocabulary size of 32,768, and a maximum context length of 2,048.
Preparing datasets: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:00<00:00, 18.89it/s]
Benchmarking:   0%|                                                                                                                                            | 0/10 [00:07<?, ?it/s]
[rank0]: Traceback (most recent call last):                                                                                                                                           
[rank0]:   File "/opt/app-root/bin/scandeval", line 8, in <module>
[rank0]:     sys.exit(benchmark())
[rank0]:              ^^^^^^^^^^^
[rank0]:   File "/opt/app-root/lib64/python3.11/site-packages/click/core.py", line 1157, in __call__
[rank0]:     return self.main(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/app-root/lib64/python3.11/site-packages/click/core.py", line 1078, in main
[rank0]:     rv = self.invoke(ctx)
[rank0]:          ^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/app-root/lib64/python3.11/site-packages/click/core.py", line 1434, in invoke
[rank0]:     return ctx.invoke(self.callback, **ctx.params)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/app-root/lib64/python3.11/site-packages/click/core.py", line 783, in invoke
[rank0]:     return __callback(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/app-root/lib64/python3.11/site-packages/scandeval/cli.py", line 288, in benchmark
[rank0]:     benchmarker(model=models)
[rank0]:   File "/opt/app-root/lib64/python3.11/site-packages/scandeval/benchmarker.py", line 642, in __call__
[rank0]:     return self.benchmark(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/app-root/lib64/python3.11/site-packages/scandeval/benchmarker.py", line 409, in benchmark
[rank0]:     benchmark_output_or_err = self._benchmark_single(
[rank0]:                               ^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/app-root/lib64/python3.11/site-packages/scandeval/benchmarker.py", line 569, in _benchmark_single
[rank0]:     scores = generate(
[rank0]:              ^^^^^^^^^
[rank0]:   File "/opt/app-root/lib64/python3.11/site-packages/scandeval/generation.py", line 79, in generate
[rank0]:     test_scores = generate_single_iteration(
[rank0]:                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/app-root/lib64/python3.11/site-packages/scandeval/generation.py", line 211, in generate_single_iteration
[rank0]:     itr_scores: dict[str, float] = model.compute_metrics(
[rank0]:                                    ^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/app-root/lib64/python3.11/site-packages/scandeval/task_utils/sequence_classification.py", line 88, in compute_metrics
[rank0]:     score_dict: dict[str, float] | None = metric.compute(
[rank0]:                                           ^^^^^^^^^^^^^^^
[rank0]:   File "/opt/app-root/lib64/python3.11/site-packages/evaluate/module.py", line 467, in compute
[rank0]:     output = self._compute(**inputs, **compute_kwargs)
[rank0]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/app-root/src/.cache/huggingface/modules/evaluate_modules/metrics/evaluate-metric--f1/0ca73f6cf92ef5a268320c697f7b940d1030f8471714bffdb6856c641b818974/f1.py", line 130, in _compute
[rank0]:     return {"f1": float(score) if score.size == 1 else score}
[rank0]:                                   ^^^^^^^^^^
[rank0]: AttributeError: 'float' object has no attribute 'size'
[rank0]:[W1213 08:25:54.533309909 ProcessGroupNCCL.cpp:1250] Warning: WARNING: process group has NOT been destroyed before we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_process_group to ensure that any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and block the progress of another member of the process group. This constraint has always been present,  but this warning has only been added since PyTorch 2.4 (function operator())```


### Operating System

Linux

### Device

CUDA GPU

### Python version

3.11.x

### ScandEval version

14.0.1

**Comment by saattrupdan** [comment] 2024-12-13 09:06
Can't reproduce. Can you try uninstalling scandeval, evaluate and transformers, and reinstalling?

Also, just FYI, when evaluating models for the leaderboards, you now have to set `--evaluate-test-split`, as it defaults to the validation split now, to avoid overfitting.

**Comment by Mikeriess** [comment] 2024-12-13 19:37
Ahh, thats too bad. Ive tried multiple versions of ScandEval now with no luck.

**Comment by saattrupdan** [comment] 2024-12-13 21:26
Can you send the version of `evaluate` you're using?

**Comment by Mikeriess** [comment] 2024-12-13 21:45
Might have located the issue; it's something with the F1 score, so I tried to downgrade scikit-learn to version 1.5.2, which seem to prevent the bug. Without having looked further into the changes in scikit-learn my guess would be that they changed the exception handling and the score object sometimes dont have a .size attribute anymore.... Could be wrong, but its benchmarking now!

**Comment by Mikeriess** [comment] 2024-12-13 21:46
```
Package                           Version
--------------------------------- --------------
absl-py                           2.1.0
accelerate                        1.2.1
aiofiles                          23.2.1
aiohappyeyeballs                  2.4.3
aiohttp                           3.10.10
aiosignal                         1.3.1
annotated-types                   0.7.0
anyio                             4.6.2.post1
argon2-cffi                       23.1.0
argon2-cffi-bindings              21.2.0
arrow                             1.3.0
asttokens                         2.4.1
async-lru                         2.0.4
attrs                             24.2.0
babel                             2.16.0
beautifulsoup4                    4.12.3
bert-score                        0.3.13
bitsandbytes                      0.45.0
bleach                            6.2.0
certifi                           2024.8.30
cffi                              1.17.1
charset-normalizer                3.4.0
chex                              0.1.88
click                             8.1.7
cloudpickle                       3.1.0
colorama                          0.4.6
comm                              0.2.2
compressed-tensors                0.8.0
contourpy                         1.3.1
cycler                            0.12.1
datasets                          3.2.0
debugpy                           1.8.7
decorator                         5.1.1
defusedxml                        0.7.1
demjson3                          3.0.6
dill                              0.3.8
diskcache                         5.6.3
distro                            1.9.0
einops                            0.8.0
etils                             1.11.0
evaluate                          0.4.3
executing                         2.1.0
fastapi                           0.115.6
fastjsonschema                    2.20.0
ffmpy                             0.4.0
filelock                          3.16.1
flash-attn                        2.7.2.post1
flax                              0.10.2
fonttools                         4.55.3
fqdn                              1.5.1
frozenlist                        1.5.0
fsspec                            2024.9.0
gguf                              0.10.0
gitdb                             4.0.11
GitPython                         3.1.43
gradio                            5.8.0
gradio_client                     1.5.1
h11                               0.14.0
httpcore                          1.0.6
httptools                         0.6.4
httpx                             0.27.2
huggingface-hub                   0.26.5
humanize                          4.11.0
idna                              3.10
importlib_metadata                8.5.0
importlib_resources               6.4.5
interegular                       0.3.3
ipykernel                         6.29.5
ipython                           8.29.0
ipywidgets                        8.1.5
isoduration                       20.11.0
jax                               0.4.37
jaxlib                            0.4.36
jedi                              0.19.1
Jinja2                            3.1.4
jiter                             0.8.2
joblib                            1.4.2
json5                             0.9.25
jsonpointer                       3.0.0
jsonschema                        4.23.0
jsonschema-specifications         2024.10.1
jupyter_client                    8.6.3
jupyter_core                      5.7.2
jupyter-events                    0.10.0
jupyter-lsp                       2.2.5
jupyter_server                    2.14.2
jupyter-server-mathjax            0.2.6
jupyter_server_proxy              4.3.0
jupyter_server_terminals          0.5.3
jupyterlab                        4.2.5
jupyterlab_git                    0.50.2
jupyterlab_pygments               0.3.0
jupyterlab_server                 2.27.3
jupyterlab_widgets                3.0.13
kiwisolver                        1.4.7
lark                              1.2.2
Levenshtein                       0.26.1
litellm                           1.55.1
llvmlite                          0.43.0
lm-format-enforcer                0.10.9
markdown-it-py                    3.0.0
MarkupSafe                        2.1.5
matplotlib                        3.9.4
matplotlib-inline                 0.1.7
mdurl                             0.1.2
micropipenv                       1.8.1
mistral_common                    1.5.1
mistune                           3.0.2
ml_dtypes                         0.5.0
more-itertools                    10.5.0
mpmath                            1.3.0
msgpack                           1.1.0
msgspec                           0.18.6
multidict                         6.1.0
multiprocess                      0.70.16
nbclient                          0.10.0
nbconvert                         7.16.4
nbdime                            4.0.2
nbformat                          5.10.4
nbgitpuller                       1.2.1
nest-asyncio                      1.6.0
networkx                          3.4.2
nltk                              3.9.1
notebook_shim                     0.2.4
numba                             0.60.0
numpy                             1.26.4
nvidia-cublas-cu12                12.4.5.8
nvidia-cuda-cupti-cu12            12.4.127
nvidia-cuda-nvrtc-cu12            12.4.127
nvidia-cuda-runtime-cu12          12.4.127
nvidia-cudnn-cu12                 9.1.0.70
nvidia-cufft-cu12                 11.2.1.3
nvidia-curand-cu12                10.3.5.147
nvidia-cusolver-cu12              11.6.1.9
nvidia-cusparse-cu12              12.3.1.170
nvidia-ml-py                      12.560.30
nvidia-nccl-cu12                  2.21.5
nvidia-nvjitlink-cu12             12.4.127
nvidia-nvtx-cu12                  12.4.127
openai                            1.57.4
opencv-python-headless            4.10.0.84
opt_einsum                        3.4.0
optax                             0.2.4
orbax-checkpoint                  0.10.2
orjson                            3.10.12
outlines                          0.0.46
overrides                         7.7.0
packaging                         24.1
pandas                            2.2.3
pandocfilters                     1.5.1
parso                             0.8.4
partial-json-parser               0.2.1.1.post4
pexpect                           4.9.0
pillow                            10.4.0
pip                               23.2.1
platformdirs                      4.3.6
prometheus_client                 0.21.0
prometheus-fastapi-instrumentator 7.0.0
prompt_toolkit                    3.0.48
propcache                         0.2.0
protobuf                          3.20.3
psutil                            6.1.0
ptyprocess                        0.7.0
pure_eval                         0.2.3
py-cpuinfo                        9.0.0
pyairports                        2.1.1
pyarrow                           18.1.0
pycountry                         24.6.1
pycparser                         2.22
pydantic                          2.10.3
pydantic_core                     2.27.1
pydub                             0.25.1
Pygments                          2.18.0
pyinfer                           0.0.3
pyparsing                         3.2.0
python-dateutil                   2.9.0.post0
python-dotenv                     1.0.1
python-json-logger                2.0.7
python-multipart                  0.0.19
pytz                              2024.2
PyYAML                            6.0.2
pyzmq                             26.2.0
RapidFuzz                         3.10.1
ray                               2.40.0
referencing                       0.35.1
regex                             2024.11.6
requests                          2.32.3
rfc3339-validator                 0.1.4
rfc3986-validator                 0.1.1
rich                              13.9.4
rouge_score                       0.1.2
rpds-py                           0.20.1
ruff                              0.8.3
sacremoses                        0.1.1
safehttpx                         0.1.6
safetensors                       0.4.5
ScandEval                         14.0.2
scikit-learn                      1.5.2
scipy                             1.14.1
semantic-version                  2.10.0
Send2Trash                        1.8.3
sentencepiece                     0.2.0
seqeval                           1.2.2
setuptools                        74.1.3
shellingham                       1.5.4
simpervisor                       1.0.0
simplejson                        3.19.3
six                               1.16.0
smmap                             5.0.1
sniffio                           1.3.1
soupsieve                         2.6
stack-data                        0.6.3
starlette                         0.41.3
sympy                             1.13.1
tabulate                          0.9.0
tenacity                          9.0.0
tensorstore                       0.1.71
termcolor                         2.5.0
terminado                         0.18.1
threadpoolctl                     3.5.0
tiktoken                          0.7.0
tinycss2                          1.4.0
tokenizers                        0.21.0
tomlkit                           0.13.2
toolz                             1.0.0
torch                             2.5.1
torchvision                       0.20.1
tornado                           6.4.1
tqdm                              4.67.1
traitlets                         5.14.3
transformers                      4.47.0
triton                            3.1.0
typer                             0.15.1
types-python-dateutil             2.9.0.20241003
typing_extensions                 4.12.2
tzdata                            2024.2
uri-template                      1.3.0
urllib3                           2.2.3
uvicorn                           0.32.1
uvloop                            0.21.0
vllm                              0.6.4.post1
watchfiles                        1.0.3
wcwidth                           0.2.13
webcolors                         24.8.0
webencodings                      0.5.1
websocket-client                  1.8.0
websockets                        14.1
wheel                             0.45.1
widgetsnbextension                4.0.13
xformers                          0.0.28.post3
xxhash                            3.5.0
yarl                              1.17.1
zipp                              3.21.0
```

**Comment by saattrupdan** [comment] 2024-12-14 07:27
Nice find! 

You're completely right, sklearn updated a handful of days ago, where this particular PR was merged in, which ensures that the F1-score now returns a float instead of a numpy scalar:

https://github.com/scikit-learn/scikit-learn/pull/27369

I assume that it will get fixed in a future `evaluate` version, but I'll set an upper bound on `sklearn` until then. Thanks!

**Comment by saattrupdan** [comment] 2024-12-14 07:49
Here's the corresponding `evaluate` issue: https://github.com/huggingface/evaluate/issues/655

**Closed** 2024-12-14 10:39 UTC
Labels: bug
